name: 🗺️ Автооновлення sitemap.xml

on:
  workflow_dispatch:             # дозволяє ручний запуск (залишаємо)
  schedule:                      # запускає щодня о 00:00 UTC
    - cron: '0 0 * * *'
  push:                          # запускає при кожному push у гілку main
    branches:
      - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧹 Очистити node_modules та кеш npm
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: 📦 Ініціалізація та встановлення залежностей
        run: |
          npm init -y
          npm install node-fetch@2 cheerio

      - name: ⚙️ Запустити генерацію sitemap.xml
        run: node generate-sitemap.js

      - name: 💾 Закомітити sitemap.xml
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml
          git commit -m "🔄 Автоматичне оновлення sitemap.xml" || echo "No changes to commit"
          git push
